backend/controllers/KeyStorageController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\KeyStorageItem;
use backend\models\search\KeyStorageItemSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use vova07\fileapi\behaviors\UploadBehavior;
use vova07\fileapi\actions\UploadAction as FileAPIUpload;


/**
 * KeyStorageController implements the CRUD actions for KeyStorageItem model.
 */
class KeyStorageController extends Controller
{
    public function behaviors()
    {
        return [
        ];
    }

public function actions()
{
    return [
        'fileapi-upload' => [
            'class' => FileAPIUpload::className(),
            'path' => '@static/temp/',
            'validatorOptions' => [
                'mimeTypes' => ['mime/type'=>'image/png'],
             ]
        ]
    ];
}

    /**
     * Lists all KeyStorageItem models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new KeyStorageItemSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->sort = [
            'defaultOrder'=>['key'=>SORT_DESC]
        ];
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new KeyStorageItem model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new KeyStorageItem();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing KeyStorageItem model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->key=='favicon'){
            $model->attachBehaviors([
                    'uploadBehavior' => [
                        'class' => UploadBehavior::className(),
                        'attributes' => [
                            'value' => [
                                'tempPath' => '@static/temp',
                                'path' => '@static/favicon',
                                'url' => Yii::getAlias('@statwww/favicon'),
                            ]
                        ]
                    ]
                ]
            
            );}
//            vd($model);
        if ($model->load(Yii::$app->request->post()) && $model->save() ) {
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing KeyStorageItem model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the KeyStorageItem model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return KeyStorageItem the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = KeyStorageItem::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\LoginForm;
use yii\filters\VerbFilter;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
         /*   'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
            */
        ];;

    }
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use frontend\models\LoginForm;
use app\models\Search;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use frontend\modules\page\models\Page;
use yii\sphinx\Query;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
                'transparent' => true, 
            ],
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'successCallback'],
            ],
        ];
    }

    public function actionSearch()
    {
        $model = new Search();
        $model->q=Yii::$app->request->get('q');
        if(!$model->validate()){
                vd($model->getErrors(),false);
        }
            return $this->render(
                'search',
                [
                    'model' => $model,
                ]
            );
    }

    public function actionAutoCompleteSearch($term)
    {
        $model = new Search();
        $model->q=Yii::$app->request->get('term');
        Yii::$app->response->format = Response::FORMAT_JSON;
        if($model->validate()){
       $index = Yii::$app->sphinx->getIndexSchema('{{%post}}')->name;
        $result = (new Query())
            ->select('content')
            ->from($index)
            ->match($model->q)
            ->andWhere('visible=1')
            ->snippetCallback(function ($rows) {
                $result=['xxx'];
                    if(count($rows)>0){
                        foreach ($rows as $id=>$row) {
                            $result[] = $row['content'];
                        }
                    unset($result[0]);
                    }
                return $result;

            }) 
            ;
        return $result->limit(5)->all();
        }
    }

    public function actionIndex()
    {
			$this->layout='main-index';
            $cache = Yii::$app->cache;
            $dependency = new \yii\caching\TagDependency(['tags'=>['page']]) ;
            $key = 'page-main'.__FILE__.__LINE__;
            $page =  $cache->get($key);
            if ($page === false) {
            $page=Page::find()->where(['slug'=>'main'])->limit(1)->one();
            $cache->set($key, $page, 60*3600, $dependency );
            }
        return $this->render('index',['main'=>$page]);
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return
            Yii::$app->getResponse()->redirect(Yii::$app->getUser()->getReturnUrl($defaultUrl));
        } else {
          return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->testEmail(Yii::$app->params['testEmail']);
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                $thanksMessage = "Спасибо за обращение!
                Мы постараемся ответить вам как можно скорее, но получаем большое количество писем, по этому, если вам нужен ответ срочно, то обратитесь к нам в Viber/WhatsApp по телефону +7-926-847-18-97";
                Yii::$app->session->setFlash('success', $thanksMessage );
            } else {
                Yii::$app->session->setFlash('error',Yii::t('app','There was a mistake, try later' ));
            }
            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->getSession()->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->getSession()->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->getSession()->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    public function successCallback($client)
    {
        $attributes = $client->getUserAttributes();
        // user login or signup comes here
    }


}

backend/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/index.php
<?php
use \yii\helpers\Url;
/* @var $this yii\web\View */

$this->title = 'Страница управления сайтом';
?>
<div class="site-index">

    <div class="jumbotron">
        <p><a class="btn btn-lg btn-success" target="_blank" href="http://<?= str_replace('admin.','',Yii::getAlias('@host'))?>">Главная страница</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Определения</h2>
                   <dl>
                    <dt>Title - Заголовок</dt>
                        <dd>Используется для <dd>
                    <dt>Slug - ЧУРЛ</dt>
                        <dd>Применяется для создания "человеко понятной" ссылки.
                            Может создаваться как вручную так и автоматически на основании title.
                            Так из title "Например" будет автоматически сформирована ссылка "naprimer".
                            Вы можете указать свой вариант.
                        </dd>
                    <dt>Caption - краткое описание</dt>
                        <dd>Используется для вывода краткого описания, которое отображается в списке. 
                        </dd>
                    <dt>Note - примечание</dt>
                        <dd>Используется для вывода дополнительной информации. Использование не обязательно.</dd>
                    <dt>Content - Содержимое</dt>
                        <dd>Собственно основной текст </dd>
                    <dt>Visible - Видимость</dt>
                        <dd>Показывать или нет на сайте.</dd>
                    <dt>Present, Box, TextBox</dt>
                        <dd>Показывать ли на главной странице в соответсвующих блоках</dd>
                    <dt>Description - описание для поисковой системы</dt>
                        <dd>Этот текст показывает поисковая система в результатах поиска.
                        </dd>
                    <dt>Keywords - ключевые слова</dt>
                        <dd>Использует поисковая система для поиска. Есть мненение что уже не особо работает.
                        </dd>
                   </dl>
            </div>

            <div class="col-lg-4">
                <h3>Общие настройки сайта</h3>
                <p>Title, description, keywords для главной </p>
                <p><a class="btn btn-default" href="<?=Url::to(['key-storage/index'])?>">Настройки&raquo;</a></p>
                <h2>Страницы</h2>

                <p>Предназначен для формирования общей навигации по сайту и создания статических страниц.
                </p>


                <p><a class="btn btn-default" href="<?=Url::to(['page/default/index'])?>">Страницы&raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Посты</h2>
                <p>Динамично имзменяемое содержимое сайта.
                    Создание новостей, альбомов,  ведение блога.
                </p>
                <h3>Категории</h3>
                <p>Категория поста. Например, новости, галлерея, статья.
                    Slug категории используется как ссылка при формировании навигации с помощью раздела страниц.
                    Если в страницах указать slug раздела, то на этой странице откроется список соответсвующих этой категории постов.
                </p>
                <p><a class="btn btn-default" href="<?=Url::to(['page/category/index'])?>">Категории&raquo;</a></p>
                <h3>Посты по категориям</h3>
                <p>После Категории в меню идут ссылки на посты соответсвующиз категория. Например, новости, галлерея, статья.
                </p>
                <p>Принцип создания постов и страниц идентичен. Разделение на категории используется для формирования разделов сайта и создания различных по оформлению страниц.
                </p>
            </div>
        </div>

    </div>
</div>

backend/views/site/login.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\widgets\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
                <?= $form->field($model, 'username') ?>
                <?= $form->field($model, 'password')->passwordInput() ?>
                <?= $form->field($model, 'rememberMe')->checkbox() ?>
                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>