common/modules/dform/models/Dform.php
<?php

namespace common\modules\dform\models;

use Yii;
use \common\modules\dform\models\base\Dform as BaseDform;
use \yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "dform".
 */
class Dform extends BaseDform
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'slug'], 'required'],
            [['created_at', 'updated_at'], 'integer'],
            [['name', 'slug'], 'string', 'max' => 25],
            [['slug'], 'match', 'pattern' => '/[\w-_]+/','message' => 'Только латинские буквы, "-", "_" и цифры']
        ];
    }
    public function behaviors() {
        return [
              [
                  'class' => TimestampBehavior::className(),
              ],
		];
	}
}

common/modules/dform/models/DformField.php
<?php

namespace common\modules\dform\models;

use Yii;
use \common\modules\dform\models\base\DformField as BaseDformField;
use \yii\behaviors\TimestampBehavior;
use \yii\helpers\ArrayHelper;

/**
 * This is the model class for table "dform_field".
 */
class DformField extends BaseDformField
{
    const TYPE_RADIOLIST = 1;
    const TYPE_CHECKBOXLIST = 2;
    const TYPE_TEXTAREA = 3;
    const TYPE_TEXTINPUT = 4;

    const VALIDATOR_STRING = 1;
    const VALIDATOR_NUMBER = 2;
    const VALIDATOR_EMAIL = 3; 

    public function getType(){
        $types = self::types();
        return $types[$this->type_id];
   }
   public static function types(){
       return [
        self::TYPE_RADIOLIST => 'radioList',
        self::TYPE_CHECKBOXLIST => 'checkboxList',
        self::TYPE_TEXTAREA => 'textarea',
        self::TYPE_TEXTINPUT => 'textInput',
       ];
  }

    public function getValidator(){
        $validators = self::validators();
        return ArrayHelper::getValue($validators, $this->validator_id, 'safe') ;
   }
   public static function validators(){
       return [
        self::VALIDATOR_STRING => 'string',
        self::VALIDATOR_NUMBER => 'number',
        self::VALIDATOR_EMAIL => 'email',
       ];
  }
    
    public function rules()
    {
        return [
            [['dform_id', 'type_id', 'validator_id', 'created_at', 'updated_at'], 'integer'],
            [['required'],'safe'],
            [['name', 'slug',], 'string', 'max' => 25],
            [['name', 'slug',], 'trim'],
            [['slug'], 'match', 'pattern' => '/^[a-zA-Z0-9_]+$/', 'message' => 'Только латинские буквы, "_" и цифры'],
            [['dform_id'], 'exist', 'skipOnError' => true, 'targetClass' => Dform::className(), 'targetAttribute' => ['dform_id' => 'id']],
        ];
    }

    public function behaviors() {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
            [
                'class' => 'sjaakp\sortable\Sortable',
            ],
		];
	}
}

common/modules/dform/models/DformFieldItem.php
<?php

namespace common\modules\dform\models;

use Yii;
use \common\modules\dform\models\base\DformFieldItem as BaseDformFieldItem;

/**
 * This is the model class for table "dform_field_item".
 */
class DformFieldItem extends BaseDformFieldItem
{
}

common/modules/dform/controllers/DefaultController.php
<?php

namespace common\modules\dform\controllers;

use yii\web\Controller;

use common\modules\dform\models\Dform;
use common\modules\dform\models\search\Dform as DformSearch;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;
use yii\base\DynamicModel;
use \yii\helpers\ArrayHelper;

class DefaultController extends Controller
{
	
	/**
	 * Lists all Dform models.
	 * @return mixed
	 */
	public function actionIndex()
	{
		$searchModel  = new DformSearch;
		$dataProvider = $searchModel->search($_GET);

		Tabs::clearLocalStorage();

        Url::remember();
        \Yii::$app->session['__crudReturnUrl'] = null;

		return $this->render('index', [
			'dataProvider' => $dataProvider,
			'searchModel' => $searchModel,
		]);
	}

    /**
	 * Displays a single Dform model.
	 * @param integer $id
     *
	 * @return mixed
	 */
	public function actionView($id)
	{
        \Yii::$app->session['__crudReturnUrl'] = Url::previous();
        Url::remember();
        Tabs::rememberActiveState();

        $form = $this->findModel($id);
//        vd(ArrayHelper::toArray($form->dformFields));
        $cols = ArrayHelper::getcolumn($form->dformFields,'slug') ;
        $model = new DynamicModel($cols);
        $dform = $form->dformFields;
        $model->attributeLabels(ArrayHelper::map($form->dformFields,'slug','name'));
        foreach ( $dform as $field){
            if ($field->required ) $model->addRule($field->slug, 'required',['message' => 'Необходимо заполнить: '. $field->name]);
            $model->addRule($field->slug, 'trim');
            $model->addRule($field->slug, $field->validator);
        }

		try {
            if ($model->load($_POST) && $model->validate()) {
                return $this->render('mail',[
                    'model' => $model,
                    'dform' => $dform
                ]);
            } else  {
                return $this->render('view', [
        			'model' => $model,
                    'dform' => $dform
		]);
            }
        } catch (\Exception $e) {
            $msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
            $model->addError('_exception', $msg);
		}
	}
	
    /**
	 * Finds the Dform model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 * @param integer $id
	 * @return Dform the loaded model
	 * @throws HttpException if the model cannot be found
	 */
	protected function findModel($id)
	{
		if (($model = Dform::findOne($id)) !== null) {
			return $model;
		} else {
			throw new HttpException(404, 'The requested page does not exist.');
		}
	}
}

common/modules/dform/controllers/DformController.php
<?php

namespace common\modules\dform\controllers;

/**
 * This is the class for controller "DformController".
 */
class DformController extends \common\modules\dform\controllers\base\DformController
{

}

common/modules/dform/controllers/DformFieldController.php
<?php

namespace common\modules\dform\controllers;

/**
 * This is the class for controller "DformFieldController".
 */
class DformFieldController extends \common\modules\dform\controllers\base\DformFieldController
{
    public function actionOrder( )   {
        $post = \Yii::$app->request->post( );
        if (isset( $post['key'], $post['pos'] ))   {
            $this->findModel( $post['key'] )->order( $post['pos'] );
        }
    }
}

common/modules/dform/controllers/DformFieldItemController.php
<?php

namespace common\modules\dform\controllers;

/**
 * This is the class for controller "DformFieldItemController".
 */
class DformFieldItemController extends \common\modules\dform\controllers\base\DformFieldItemController
{

}

common/modules/dform/views/default/index.php
<div class="dform-default-index">
    <h1><?= $this->context->action->uniqueId ?></h1>
    <p>
        This is the view content for action "<?= $this->context->action->id ?>".
        The action belongs to the controller "<?= get_class($this->context) ?>"
        in the "<?= $this->context->module->id ?>" module.
    </p>
    <p>
        You may customize this page by editing the following file:<br>
        <code><?= __FILE__ ?></code>
    </p>
</div>

common/modules/dform/views/default/mail.php
<?php

//use yii\helpers\Html;
use yii\bootstrap\Html;
use \yii\helpers\ArrayHelper;

echo __FILE__;
?>

<div class="">
<h1><?= $this->context->action->uniqueId ?></h1>

    <div class="form-horizontal">

        <p>

<?php
    foreach ($dform as $field){
     $type = $field->type;
     $attr = $field->slug;
echo Html::beginTag('div', ['class'=>'row']);
  if ( $list = $field->dformFieldItems){
        echo Html::tag('label', $field->name,['class'=>'col-sm-3 control-label']);
        echo Html::beginTag('div',['class'=>'col-sm-6']);
    foreach (ArrayHelper::map($list,'id','value') as $value=>$label){
            $selection = $model->$attr ;
            $checked = $selection !== null &&
                (!is_array($selection) && !strcmp($value, $selection)
                    || is_array($selection) && in_array($value, $selection));
        $ch = ( $checked ) ? ' - V' : ' - x' ;
        echo Html::tag('div', $label . $ch );
    }
        echo Html::endTag('div');
      } else {
        echo Html::tag('label',$field->name,['class'=>'col-sm-3 control-label ']);
echo Html::beginTag('div',['class'=>'col-sm-6']);
        echo Html::tag('span', $model->$attr);
echo Html::endTag('div');
      }
echo Html::endTag('div');
 }
/*
    foreach ($dform as $field){
     $type = $field->type;
     $attr = $field->slug;
echo Html::beginTag('div', ['class'=>'form-group']);
  if ( $list = $field->dformFieldItems){
        echo Html::tag('label',$field->name,['class'=>'col-sm-3 control-label ']);
        $input=substr($type,0,strpos($type,'List'));
            $options['item'] = function ($index, $label, $name, $checked, $value) use ($input) {
                return '<div class="checkbox">' . Html::$input($name, $checked, ['label' => $label, 'value' => $value, 'disabled'=>true]) . '</div>';
                };
            $options['class']='radio col-sm-6';
            $options['itemOptions']=['readonly'=>true];
        echo Html::$type($field->slug,$model->$attr,ArrayHelper::map($list,'id','value'), $options );
      } else {
        echo Html::tag('label',$field->name,['class'=>'col-sm-3 control-label ']);
echo Html::beginTag('div',['class'=>'radio col-sm-6']);
            unset($options);
            $options['readonly']=true;
        echo Html::$type($field->slug, $model->$attr, $options );
echo Html::endTag('div'); 
      }
echo Html::endTag('div'); 
 }
*/
?>
        <hr/>

    </div>

</div>

<?php

common/modules/dform/views/default/view.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use \yii\helpers\ArrayHelper;

?>

<div class="">
<h1><?= $this->context->action->uniqueId ?></h1>
<?php
    $form = ActiveForm::begin([
    'id' => 'DformField',
    'layout' => 'horizontal',
    'enableClientValidation' => false, // true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
    ]
    );
    ?>

    <div class="">

        <p>

<?php
    foreach ($dform as $field){?>
<?php
     $type = $field->type;
     $list = ArrayHelper::map($field->dformFieldItems,'id','value') ;
?>

<?= $form->field($model, $field->slug)
    ->label($field->name)
    ->$type($list) ?>
<?php 
     } ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
            //($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save')),
        Yii::t('app', 'Save'),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

common/modules/dform/views/dform-field/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use common\modules\dform\models\DformField;

/**
* @var yii\web\View $this
* @var common\modules\dform\models\DformField $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="dform-field-form">

    <?php $form = ActiveForm::begin([
    'id' => 'DformField',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
			<?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'slug')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'required')->checkbox() ?>
            
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'dform_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(common\modules\dform\models\Dform::find()->all(), 'id', 'name'),
    ['prompt' => Yii::t('app', 'Select')]
); ?>
            <?=$form->field($model, 'type_id')->dropDownList( DformField::types(),
             ['prompt' => Yii::t('app', 'Select')]
            ); ?>
            <?=$form->field($model, 'validator_id')->dropDownList( DformField::validators(),
             ['prompt' => Yii::t('app', 'Select')]
            ); ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                   'encodeLabels' => false,
                     'items' => [ [
    'label'   => 'DformField',
    'content' => $this->blocks['main'],
    'active'  => true,
], ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save')),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

common/modules/dform/views/dform-field/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
* @var yii\web\View $this
* @var common\modules\dform\models\search\DformField $model
* @var yii\widgets\ActiveForm $form
*/
?>

<div class="dform-field-search">

    <?php $form = ActiveForm::begin([
    'action' => ['index'],
    'method' => 'get',
    ]); ?>

    		<?= $form->field($model, 'id') ?>

		<?= $form->field($model, 'dform_id') ?>

		<?= $form->field($model, 'name') ?>

		<?= $form->field($model, 'type_id') ?>

		<?= $form->field($model, 'validator_id') ?>

		<?php // echo $form->field($model, 'created_at') ?>

		<?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

common/modules/dform/views/dform-field/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/**
* @var yii\web\View $this
* @var yii\data\ActiveDataProvider $dataProvider
    * @var common\modules\dform\models\search\DformField $searchModel
*/

$this->title = Yii::t('app', 'Dform Fields');
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="giiant-crud dform-field-index">

    <?php //             echo $this->render('_search', ['model' =>$searchModel]);
        ?>

    
    <?php \yii\widgets\Pjax::begin(['id'=>'pjax-main', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>

    <h1>
        <?= Yii::t('app', 'Dform Fields') ?>        <small>
            List
        </small>
    </h1>
    <div class="clearfix crud-navigation">
        <div class="pull-left">
            <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New'), ['create'], ['class' => 'btn btn-success']) ?>
        </div>

        <div class="pull-right">

                                                                                
            <?= 
            \yii\bootstrap\ButtonDropdown::widget(
            [
            'id' => 'giiant-relations',
            'encodeLabel' => false,
            'label' => '<span class="glyphicon glyphicon-paperclip"></span> ' . Yii::t('app', 'Relations'),
            'dropdown' => [
            'options' => [
            'class' => 'dropdown-menu-right'
            ],
            'encodeLabels' => false,
            'items' => [            [
                'url' => ['dform/index'],
                'label' => '<i class="glyphicon glyphicon-arrow-right">&nbsp;' . Yii::t('app', 'Dform') . '</i>',
            ],            [
                'url' => ['dform-field-item/index'],
                'label' => '<i class="glyphicon glyphicon-arrow-right">&nbsp;' . Yii::t('app', 'Dform Field Item') . '</i>',
            ],]
            ],
            'options' => [
            'class' => 'btn-default'
            ]
            ]
            );
            ?>        </div>
    </div>


    <div class="table-responsive">
        <?= GridView::widget([
        'layout' => '{summary}{pager}{items}{pager}',
        'dataProvider' => $dataProvider,
        'pager' => [
        'class' => yii\widgets\LinkPager::className(),
        'firstPageLabel' => Yii::t('app', 'First'),
        'lastPageLabel' => Yii::t('app', 'Last')        ],
                    'filterModel' => $searchModel,
                'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
        'headerRowOptions' => ['class'=>'x'],
        'columns' => [

                [
            'class' => 'yii\grid\ActionColumn',
            'urlCreator' => function($action, $model, $key, $index) {
                // using the column name as key, not mapping to 'id' like the standard generator
                $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
                $params[0] = \Yii::$app->controller->id ? \Yii::$app->controller->id . '/' . $action : $action;
                return Url::toRoute($params);
            },
            'contentOptions' => ['nowrap'=>'nowrap']
        ],
			// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'dform_id',
    'value' => function ($model) {
        if ($rel = $model->getDform()->one()) {
            return Html::a($rel->name, ['dform/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'type_id',
    'value' => function ($model) {
        if ($name = $model->getType($model->type_id)) {
            return $name;
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'validator_id',
    'value' => function ($model) {
        if ($name = $model->getValidator($model->validator_id)) {
            return $name;
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
			'updated_at:date',
			'name',
        ],
        ]); ?>
    </div>

</div>


<?php \yii\widgets\Pjax::end() ?>

common/modules/dform/views/dform-field/view.php
<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var common\modules\dform\models\DformField $model
*/
$copyParams = $model->attributes;

$this->title = 'Dform Field ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Dform Fields', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'View');
?>
<div class="giiant-crud dform-field-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        <?= Yii::t('app', 'Dform Field') ?>        <small>
            <?= $model->name ?>        </small>
    </h1>



    <div class="clearfix crud-navigation">
        <!-- menu buttons -->
        <div class='pull-left'>
            <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('app', 'Edit'), ['update', 'id' => $model->id],['class' => 'btn btn-info']) ?>
            <?= Html::a('<span class="glyphicon glyphicon-copy"></span> ' . Yii::t('app', 'Copy'), ['create', 'id' => $model->id, 'DformField'=>$copyParams],['class' => 'btn btn-success']) ?>
            <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New'), ['create'], ['class' => 'btn btn-success']) ?>
        </div>
        <div class="pull-right">
            <?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . Yii::t('app', 'List DformFields'), ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>


    <?php $this->beginBlock('common\modules\dform\models\DformField'); ?>

    
    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
            'id',
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'dform_id',
    'value' => ($model->getDform()->one() ? Html::a($model->getDform()->one()->name, ['dform/view', 'id' => $model->getDform()->one()->id,]) : '<span class="label label-warning">?</span>'),
],
        'name',
        'type_id',
        'validator_id',
        'created_at',
        'updated_at',
    ],
    ]); ?>

    
    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('app', 'Delete'), ['delete', 'id' => $model->id],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . Yii::t('app', 'Are you sure to delete this item?') . '',
    'data-method' => 'post',
    ]); ?>
    <?php $this->endBlock(); ?>


    
<?php $this->beginBlock('DformFieldItems'); ?>
<div style='position: relative'><div style='position:absolute; right: 0px; top: 0px;'>
  <?= Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('app', 'List All') . ' Dform Field Items',
            ['dform-field-item/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New') . ' Dform Field Item',
            ['dform-field-item/create', 'DformFieldItem' => ['field_id' => $model->id]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div></div><?php Pjax::begin(['id'=>'pjax-DformFieldItems', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-DformFieldItems ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>
<?= '<div class="table-responsive">' . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getDformFieldItems(), 'pagination' => ['pageSize' => 20, 'pageParam'=>'page-dformfielditems']]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => Yii::t('app', 'First'),
        'lastPageLabel'  => Yii::t('app', 'Last')
    ],
    'columns' => [[
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'dform-field-item' . '/' . $action;
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'dform-field-item'
],
        'value',
]
]) . '</div>' ?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


    <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [ [
    'label'   => '<b class=""># '.$model->id.'</b>',
    'content' => $this->blocks['common\modules\dform\models\DformField'],
    'active'  => true,
],[
    'content' => $this->blocks['DformFieldItems'],
    'label'   => '<small>Dform Field Items <span class="badge badge-default">'.count($model->getDformFieldItems()->asArray()->all()).'</span></small>',
    'active'  => false,
], ]
                 ]
    );
    ?>
</div>

common/modules/dform/views/dform/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/**
* @var yii\web\View $this
* @var yii\data\ActiveDataProvider $dataProvider
    * @var common\modules\dform\models\search\Dform $searchModel
*/

$this->title = Yii::t('app', 'Dforms');
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="giiant-crud dform-index">

    <?php //             echo $this->render('_search', ['model' =>$searchModel]);
        ?>

    
    <?php \yii\widgets\Pjax::begin(['id'=>'pjax-main', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>

    <h1>
        <?= Yii::t('app', 'Dforms') ?>        <small>
            List
        </small>
    </h1>
    <div class="clearfix crud-navigation">
        <div class="pull-left">
            <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New'), ['create'], ['class' => 'btn btn-success']) ?>
        </div>

        <div class="pull-right">

                                                    
            <?= 
            \yii\bootstrap\ButtonDropdown::widget(
            [
            'id' => 'giiant-relations',
            'encodeLabel' => false,
            'label' => '<span class="glyphicon glyphicon-paperclip"></span> ' . Yii::t('app', 'Relations'),
            'dropdown' => [
            'options' => [
            'class' => 'dropdown-menu-right'
            ],
            'encodeLabels' => false,
            'items' => [            [
                'url' => ['dform-field/index'],
                'label' => '<i class="glyphicon glyphicon-arrow-right">&nbsp;' . Yii::t('app', 'Dform Field') . '</i>',
            ],]
            ],
            'options' => [
            'class' => 'btn-default'
            ]
            ]
            );
            ?>        </div>
    </div>


    <div class="table-responsive">
        <?= GridView::widget([
        'layout' => '{summary}{pager}{items}{pager}',
        'dataProvider' => $dataProvider,
        'pager' => [
        'class' => yii\widgets\LinkPager::className(),
        'firstPageLabel' => Yii::t('app', 'First'),
        'lastPageLabel' => Yii::t('app', 'Last')        ],
                    'filterModel' => $searchModel,
                'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
        'headerRowOptions' => ['class'=>'x'],
        'columns' => [

                [
            'class' => 'yii\grid\ActionColumn',
            'urlCreator' => function($action, $model, $key, $index) {
                // using the column name as key, not mapping to 'id' like the standard generator
                $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
                $params[0] = \Yii::$app->controller->id ? \Yii::$app->controller->id . '/' . $action : $action;
                return Url::toRoute($params);
            },
            'contentOptions' => ['nowrap'=>'nowrap']
        ],
			'name',
			'slug',
			'updated_at:date',
        ],
        ]); ?>
    </div>

</div>


<?php \yii\widgets\Pjax::end() ?>